services:
    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: mustak
            POSTGRES_PASSWORD: CookiesNwaffles@8747#$
            POSTGRES_DB: cookiesnwaffles
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

    admin:
        build:
            context: ./admin
            dockerfile: Dockerfile.dev
        container_name: strapi_admin
        env_file:
            - ./admin/.env
        volumes:
            - ./admin:/app
            - /app/node_modules
        depends_on:
            - db
        networks:
            - app_network
        ports:
            - 1337:1337

    # frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile
    #         target: production
    #     container_name: nextjs_frontend
    #     environment:
    #         NODE_ENV: production
    #     volumes:
    #         - ./frontend:/app
    #         - /app/node_modules
    #     depends_on:
    #         - admin
    #     networks:
    #         - app_network
    #     ports:
    #         - 3000:3000
    #     command: npm start

networks:
    app_network:

volumes:
    postgres_data:
